import type { Language } from "@/types/tour"; 

export const tourCategoryLabels: Record<string, Record<Language, string>> = {
  "scuba-diving": {
    en: "Scuba Diving",
    de: "Tauchen",
    it: "Immersioni",
    ru: "Дайвинг",
    pl: "Nurkowanie",
    cz: "Potápění",
    fr: "Plongée Sous-Marine",
    nl: "Duiken",
    hu: "Búvárkodás",
  },
  snorkeling: {
    en: "Snorkeling Trips",
    de: "Schnorcheln",
    it: "Snorkeling",
    ru: "Сноркелинг",
    pl: "Snorkeling",
    cz: "Šnorchlování",
    fr: "Snorkeling",
    nl: "Snorkelen",
    hu: "Sznorkelezés",
  },
  "sea-trips": {
    en: "Sea Trips",
    de: "Meeresausflüge",
    it: "Gite in Barca",
    ru: "Морские Прогулки",
    pl: "Wycieczki Morskie",
    cz: "Mořské Výlety",
    fr: "Excursions en Mer",
    nl: "Boottochten",
    hu: "Tengeri Kirándulások",
  },
  safari: {
    en: "Desert Safari",
    de: "Wüstensafari",
    it: "Safari nel Deserto",
    ru: "Сафари",
    pl: "Safari",
    cz: "Safari",
    fr: "Safari Désert",
    nl: "Woestijnsafari",
    hu: "Sivatagi Szafari",
  },
  courses: {
    en: "Diving Courses",
    de: "Tauchkurse",
    it: "Corsi Subacquei",
    ru: "Курсы Дайвинга",
    pl: "Kursy Nurkowe",
    cz: "Potápěčské Kurzy",
    fr: "Cours de Plongée",
    nl: "Duikcursussen",
    hu: "Búvártanfolyamok",
  },
  "city-tours": {
    en: "City & Sightseeing",
    de: "Städte & Kultur",
    it: "Tour della Città",
    ru: "Экскурсии по Городам",
    pl: "Wycieczki Miejskie",
    cz: "Městské Tours",
    fr: "Visites de la Ville",
    nl: "Stadstours",
    hu: "Városnézés",
  },
};